### ISSUE TITLE
 amq broker pod error Cause: User name [null] or password is invalid.

### ISSUE THREAD

**Issue by yeganx** [jboss-openshift/application-templates#208]
why my cdi-camel-mq-archtype can not sent message to activemq broker ?
I set in jololika web console prefrence user name and password , also chek it in brocker pod shell : vi /opt/amq/conf/user.properties , it was successfully configured , but not user error occured 
#oc get pods
NAME                                  READY     STATUS      RESTARTS   AGE
broker-amq-4-u3xxv                    1/1       Running     0          51s
s2i-quickstart-cdi-camel-mq-1-build   0/1       Completed   0          15h
s2i-quickstart-cdi-camel-mq-3-1pvaa   1/1       Running     0          45s
#oc logs s2i-quickstart-cdi-camel-mq-3-1pvaa | tail -20
	at org.apache.activemq.transport.AbstractInactivityMonitor.onCommand(AbstractInactivityMonitor.java:300)
	at org.apache.activemq.transport.TransportSupport.doConsume(TransportSupport.java:83)
	at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:214)
	at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:196)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.security.auth.login.FailedLoginException: user name is null
	at org.apache.activemq.jaas.PropertiesLoginModule.login(PropertiesLoginModule.java:84)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
	at org.apache.activemq.security.JaasAuthenticationBroker.authenticate(JaasAuthenticationBroker.java:84)
	... 14 more
2016-11-13 02:24:44,545 [sumer[TEST.FOO]] ERROR ultJmsMessageListenerContainer - Could not refresh JMS Connection for destination 'TEST.FOO' - retrying in 5000 ms. Cause: User name [null] or password is invalid.
# oc logs broker-amq-4-u3xxv | tail -20
 WARN | Failed to add Connection ID:s2i-quickstart-cdi-camel-mq-3-1pvaa-37212-1479021841288-1:70 due to java.lang.SecurityException: User name [null] or password is invalid.
 WARN | Security Error occurred on connection to: tcp://10.1.0.1:39184, User name [null] or password is invalid.
 WARN | Failed to add Connection ID:s2i-quickstart-cdi-camel-mq-3-1pvaa-37212-1479021841288-1:71 due to java.lang.SecurityException: User name [null] or password is invalid.
 WARN | Security Error occurred on connection to: tcp://10.1.0.1:39192, User name [null] or password is invalid.
 INFO | Stopping tcp://10.1.0.1:39176 because Failed with SecurityException: User name [null] or password is invalid.
 WARN | Failed to add Connection ID:s2i-quickstart-cdi-camel-mq-3-1pvaa-37212-1479021841288-1:72 due to java.lang.SecurityException: User name [null] or password is invalid.
 WARN | Security Error occurred on connection to: tcp://10.1.0.1:39202, User name [null] or password is invalid.
 INFO | Stopping tcp://10.1.0.1:39184 because Failed with SecurityException: User name [null] or password is invalid.
 WARN | Failed to add Connection ID:s2i-quickstart-cdi-camel-mq-3-1pvaa-37212-1479021841288-1:73 due to java.lang.SecurityException: User name [null] or password is invalid.
 WARN | Security Error occurred on connection to: tcp://10.1.0.1:39204, User name [null] or password is invalid.
 INFO | Stopping tcp://10.1.0.1:39192 because Failed with SecurityException: User name [null] or password is invalid.
 WARN | Failed to add Connection ID:s2i-quickstart-cdi-camel-mq-3-1pvaa-37212-1479021841288-1:74 due to java.lang.SecurityException: User name [null] or password is invalid.
 WARN | Security Error occurred on connection to: tcp://10.1.0.1:39212, User name [null] or password is invalid.
 INFO | Stopping tcp://10.1.0.1:39202 because Failed with SecurityException: User name [null] or password is invalid.
 WARN | Failed to add Connection ID:s2i-quickstart-cdi-camel-mq-3-1pvaa-37212-1479021841288-1:75 due to java.lang.SecurityException: User name [null] or password is invalid.
 WARN | Security Error occurred on connection to: tcp://10.1.0.1:39220, User name [null] or password is invalid.
 INFO | Stopping tcp://10.1.0.1:39204 because Failed with SecurityException: User name [null] or password is invalid.
 WARN | Failed to add Connection ID:s2i-quickstart-cdi-camel-mq-3-1pvaa-37212-1479021841288-1:76 due to java.lang.SecurityException: User name [null] or password is invalid.
 WARN | Security Error occurred on connection to: tcp://10.1.0.1:39228, User name [null] or password is invalid.
 INFO | Stopping tcp://10.1.0.1:39212 because Failed with SecurityException: User name [null] or password is invalid.

**Comment by rcernich** [comment]
It looks like you don't have security configured properly on the client: User name [null].  Unless you configured "null" as the user name.
