### ISSUE TITLE
Deploying sample war to AWS Elasticbeanstalk with Zero Downtime

### ISSUE THREAD

**Issue by Arun129** [jboss-openshift/application-templates#210]
Hi,

I am trying to deploy a sample war file from jenkins to AWS Elastic Beanstalk(Choosing tomcat inside).

I have used AWS EB Deployer plugin to achieve this. I can able to deploy to AWS Elastic Beanstalk by default, but I am unable to do zero downtime deployment in that.

If I check the Zero downtime check box, I am getting the below error:

Environment Status is 'Ready' and Health is 'Green'. Moving on.
Deployment marked as 'successful'. Starting post-deployment cleanup.
Swapping CNAMEs from environment env1 to env2
FATAL: Deployment Failure
java.io.IOException: Deployment Failure
	at br.com.ingenieux.jenkins.plugins.awsebdeployment.AWSEBDeploymentBuilder.perform(AWSEBDeploymentBuilder.java:171)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalk.swapEnvironmentCNAMEs(Lcom/amazonaws/services/elasticbeanstalk/model/SwapEnvironmentCNAMEsRequest;)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at hudson.remoting.LocalChannel$2.get(LocalChannel.java:77)
	at br.com.ingenieux.jenkins.plugins.awsebdeployment.DeployerRunner.perform(DeployerRunner.java:66)
	at br.com.ingenieux.jenkins.plugins.awsebdeployment.AWSEBDeploymentBuilder.perform(AWSEBDeploymentBuilder.java:167)
	... 9 more
Caused by: java.lang.NoSuchMethodError: com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalk.swapEnvironmentCNAMEs(Lcom/amazonaws/services/elasticbeanstalk/model/SwapEnvironmentCNAMEsRequest;)V
	at br.com.ingenieux.jenkins.plugins.awsebdeployment.cmd.ZeroDowntime.swapEnvironmentCnames(ZeroDowntime.java:142)
	at br.com.ingenieux.jenkins.plugins.awsebdeployment.cmd.ZeroDowntime.release(ZeroDowntime.java:181)
	at br.com.ingenieux.jenkins.plugins.awsebdeployment.cmd.DeployerChain.perform(DeployerChain.java:70)
	at br.com.ingenieux.jenkins.plugins.awsebdeployment.SlaveDeployerCallable.call(SlaveDeployerCallable.java:42)
	at br.com.ingenieux.jenkins.plugins.awsebdeployment.SlaveDeployerCallable.call(SlaveDeployerCallable.java:27)
	at hudson.remoting.LocalChannel$1.call(LocalChannel.java:52)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE

Any Ideas???

**Comment by josefkarasek** [comment]
This issues doesn't seem to be connected to JBoss application templates for OpenShift. I guess the right place where to put this is AWS support.
Cheers

**Comment by Arun129** [comment]
Sorry...Extremely Sorry...
